// each idea contains an ID, a name, a description and a source

var ideas = new Array(
new Array(30,"“Electronic memo”","<p>Explore how to capture the intention behind sending a physical, paper memo “when something is really important, and it cannot be <i>just</i> an e-mail” without using paper.</p><p>An exploration of this kind is likely to establish how many levels of importance and relevance can be handled effectively in the Powergen Group environment.</p>",5, 1,1,3,3,"",""),
new Array(25,"Clean desktop","<p>Make available technology to reduce clutter in the physical office environment. Examples include:<ul><li>Wireless keyboard and mouse, which reduces the clutter of wiring on the desktop and also makes informal use of the computer easier in meeting situations;<li>Wireless synchronisation of PDAs and/or cell phones, removing the need for cradles and interface cables;<li>Screen-and-graphics-tablet combinations (such as the <a href=http://www.wacom.com/lcdtablets/index.cfm target=_blank>Wacom Cintiq</a>), or touchscreens, proide a less cluttered and more direct way of reading information and interacting simply (works well with a wireless keyboard).</ul></p>",1, 1,1,1,1,"",""),
new Array(26,"Electronic transcription of paper notes","<p>Explore ways to integrate more effectively with those who like to work on paper.</p><p>This can be addressed in three ways:<ol><li>Efficient ways of making paper notes and documents available in computer form (eg, local scanners, OCR, fax-to-PDF services (proprietary or public, such as <a href=http://www.yac.com target=_blank>Yac</a>));<li>Ways of combining directly paper and electronic note taking and annotation (eg, the IBM CrossPad or <a href=http://commerce-13.www.ibm.com/cgi-bin/ncommerce/ProductDisplay?prrfnbr=2510320&cntrfnbr=1&prmenbr=1&cntry=826&lang=en_GB&scrfnbr=20&shoptype=D target=_blank>Transnote</a>, or the  <a href=http://www.seikosmart.com/products/sp582.html target=_blank>Seiko SmartPad</a>);<li>Ways of entering information directly to avoid the need for paper at all (eg, the <a href=http://www.wacom.com/lcdtablets/index.cfm target=_blank>Wacom Cintiq</a>, the <a href=http://www.panasonic.com/computer/notebook/html/01a07.htm target=_blank>Panasonic Toughbook 07</a> or emerging “<a href=http://www.microsoft.com/PressPass/press/2001/Mar01/03-26WinHECTabletPCPR.asp target=_blank>tablet computers</a>” ).</ol></p>",5, 1,2,3,3,"",""),
new Array(17,"Larger screens","<p>See whether those who have trouble reading and/or editing  documents on screen would work better with larger/multiple screens.</p><p>Consider:<ul><li><a href=http://www.tridentonline.co.uk/samsung/lcdmonitor/sm240ttft.shtml target=_blank>Samsung SyncMaster 240T</a> (1920×1200);<li><a href=http://commerce.www.ibm.com/cgi-bin/ncommerce/ProductDisplay?cntrfnbr=1&prmenbr=1&prnbr=9503DG0&cntry=840&lang=en_US target=_blank>IBM T220</a> (3840×2400).</ul></p>",1, 1,1,3,1,"",""),
new Array(29,"Automatic dictation","<p>Examine, for those who make heavy use of dictation and have identified it as valuable to them, the market-leading automatic speech recognition (ASR) products. Consider:<ul><li>L&H/Dragon/Kurzweil;<li>IBM;<li>Philips.</ul></p>",5, 1,4,3,3,"",""),
new Array(24,"PA development","<p>Exploit the close relationships between PAs and assistees by giving the PAs a role in producing measurable improvements in collaborative behaviour.</p><p>There are many ways in which PAs can affect behaviour in those they assist, from simple reminders about tasks to planning between PAs about specific issues. Implementing a scheme like this would require at least:<ul><li>A clear assessment of the relative skills of the PAs and their willingness to participate;<li>A clear statement of objectives, agreed by the PA and the assistee;<li>Training and support for the PA;<li>Defined ways of measuring progress;<li>A feedback mechanism to ensure that the objectives remain relevant and that progress is being achieved.</ul></p>",2, 1,1,2,1,"",""),
new Array(18,"Visible presence","<p>Provide group members with a real-time indication of the status of other members, to create awareness of the possibilities of communication (so that (eg,) the notion of “dropping in” to see someone becomes available remotely).</p><p>The display of statuses should be:<ul><li>Adjustable for each member to show relevant statuses;<li>Easy to keep “always on” (eg, could be displayed on a docked iPaq; could be zoomed very small);<li>Functional, so that appropriate communication can be initiated by a touch/click</ul></p><p>The actual status displays could be a combination of:<ul><li>Icons with information caption indicating where an individual is (“in a meeting”; “away from my desk”);<li>A recently updated still image;<li>A video feed (eg, from the member’s office).</ul></p>",5, 1,1,3,3,"",""),
new Array(14,"SMS hub","<p>Builds on the idea of SMS on the desktop by integrating more routing and processing intelligence into SMS. Examples features include:<ul><li>Smart “follow me” functionality to allow SMS messages to be re-routed to other media (instant on-screen messaging; e-mail; fax) where necessary;<li>Structured messaging, allowing (eg,) authorisation requests to be sent as SMS messages that display “yes” and “no” buttons to the recipient (coping with multiple handset types by knowing, in advance, about the inventory of handsets).</ul></p>",2, 1,2,3,1,"",""),
new Array(13,"SMS on the desktop","<p>Provide the ability to send and receive text messages as quickly and conveniently as possible from the desktop (<font face=symbol>&#222;</font> could be browser based, but might want an applet or even a small application for maximum speed).</p><p>Use CLID to route incoming SMS messages to appropriate desktop (eg, group member or PA).</p><p>Allow broadcast to all or selected group members.</p><p>Consider ICQ SMS mailboxes (although these have issues of security and quality of service which may make them impractical for (eg,) the directors).</p>",2, 1,2,3,1,"",""),
new Array(11,"“Network car” for comms in rural US","<p>For travel to rural US where cellular networks may be unavailable, fit a small server with a wireless LAN (for use when parked on a connected Powergen site) and a satellite link (for use when out of range) into a corporate car, and use a wireless LAN to laptop or iPaq.</p><p>The car server can cache relevant content in advance (eg, of a trip) to make it available to group member when in car without the need to go on line.</p><p>The driver could erect a temporary antenna mast to extend local range of the wireless LAN.</p><p>The  car becomes a mobile base so that passengers can retain wireless LAN flexibility wherever they go.</p>",1, 1,1,3,3,"",""),
new Array(28,"Dedicated director’s workstation","<p>Provide a dedicated PC that addresses a variety of key accessibility issues.</p><p>The “directors’ workstation” combines a powerful PC with one or two large LCD touch screen displays, a wireless keyboard and mouse and a non-contact smart card authentication mechanism.</p><p>Key features of the workstation in use are:<ul><li>Portable, instant-on environment &#151; walk up to/sit down at any directors’ workstation (anywhere in Powergen) and your environment will be available near-instantly without the need (eg,) to log in with a username and password;<li>Key functionality always available &#151; either by dedicating one of two screens, or by using a “hard” area on a single screen, key functionality (cf. the “directors’ dashboard”) would be permanently available.</ul></p>",5, 1,1,3,3,"",""),
new Array(10,"Wireless access to e-mail and documents on Powergen sites","<p>Provide a wireless LAN in Powergen sites for iPaqs.</p><p>Exploit the “trusted device” nature of the PDA (ensuring appropriate security on the device itself) to make wireless LAN roaming as seamless as possible, so that:<ul><li>It is possible to move from one Powergen building to another without reconfiguring services;<li>If there are limitations of service at a site, the device should report them actively rather than merely not working (this may require a minimal wireless LAN implementation everywhere);<li>Appropriately secure access is also available through public wireless LAN nodes (eg, <a href=http://www.nwfusion.com/news/2001/0625starbucks.html target=_blank>IEEE802.11b nodes in Starbucks coffee shops</a>);<li>Appropriately secure access is also available in group members’ homes, where they are prepared to have this facility.</ul></p><p>The wireless LAN may also be used for laptops, for those that carry one.</p><p>A further possibility for integration is to adopt so-called “4G” by combining the wireless LAN with GPRS for push and remote content.</p>",1, 1,1,3,3,"",""),
new Array(1,"Directors’ “dashboard”","<p>An information area dedicated to each director and controlled (completely/partly) by her/his PA.</p><p>Features could include:<ul><li>Short list of important impending appointments (whether from paper or electronic calendar);<li>Important messages (addressing the need to highlight important communications and tasks), deliberately limited to ensure that PA maintains this as just the key information<li>Requested documents &#151; any document requested by the director should be available for reading and/or download through the dashboard.</ul></p><p>For maximum flexibility, the dashboard should be available over a variety of channels, including:<ul><li>Intranet, (secure) Web, PDA (ideally through wireless LAN);<li>Voice &#151; it should bve possible to dial into a voice portal to hear an overview of the content of the dashboard and to make requests for documents and other information to be delivered through...<li>Fax, both on request from other channels and in “fax poll” mode;<li>SMS, so that key events in the dashboard should alert automatically, and short information should be deliverable through SMS.</ul></p><p>For some, very high availability of the dashboard is critical to its usefulness (see also the “director’s workstation” idea).</p><p>See <a href=dashboard_visualisation.exe>visualisation</a>.</p>",3, 1,2,5,3,"To create a list of functional element and decide which channels they need to be available through. This will also require a large build element and an accompanying change initiative.","Powergen looking into the possibility of using Plumtree"),
new Array(21,"Group seminars and supporting intranet sites","<p>Provide a service to support issue-related discussions and meetings, conducted on line where possible.</p><p>As well as the usual functions have such discussions, making the service available to all group members distributes repsonsibility for organising and promoting them.</p>",4, 2,4,5,2,"",""),
new Array(34,"M&A team + workflow extranet","<p>A site that helps Caroline Sheers to get teams going in <2-3 weeks. Features to be explored, but could include:<ul><li>Team directory, with biographies and pictures;<li>Logistics tracking &#151; allow the team members to see how their own and others&#146;s relocations are progressing;<li>Distribution of key software;<li>Distribution of initial &#147;get up to speed&#148; documentation.</ul>Could include/be integrated with/link to some deal room system.</p>",1, 2,3,5,3,"",""),
new Array(33,"Meeting intranet","<p>Provide a site to support meetings. Features include:<ul><li>Ability to book meetings and provide a depository for the most up-to-date documents;<li>Ability to alert participants about the location of the depository and the update of documents within it (particularly if you have already read a document but it has since been updated);<li>Ability for the meeting organiser to identify submission commitments and have them automatically chased up;<li>Easy printing of complete “meeting packs” of documentation;<li>Capturing of site-specific printing issues (eg, colour mappings) to advise recipients of printed packs of any issues there might be with what they have received.</ul></p>",3, 2,2,5,3,"",""),
new Array(19,"Virtual team working","<p>Introduce shared workspace tools such as <a href=http://www.eroom.com target=_blank>eRoom</a>, <a href=http://www.groove.net target=_blank>Groove</a> or <a href=http://www.webex.com target=_blank>WebEx</a>.</p><p>These technologies can all be trialled without major infrastructure investment. Key issues within the group (and particularly with the directors) are likely to be:<ul><li>Learning curve, both for the individual package and for the particular model of collaboration it uses.<li>Fitness for purpose &#151; is it obvious to each member what kind of work is best done/discussed within these shared workspaces?</ul></p><p>These issues can be mitigated by:<ul><li>Identifying relevant key needs (eg, a report to deliver) and rolling a tool out in the context of that need;<li>Nominating and training individuals within the group to act as custodians and evangelists for the tools.</ul></p>",3, 2,2,5,4,"",""),
new Array(2,"Improved press cuttings","<p>Improve the interactive service by (eg,):<ul><li>Having a proper index of headline/first line on the front;<li>Order the headlines by subject relevant to the focus of the reader;<li>Allow clippings to be delivered to iPaq (eg, through AvantGo);<li>Allow a “keep me posted” request so that a reader can be explicitly notified (by e-mail, or just by highlighting relevant clippings in subsequent issues) of developments in a particular issue.</ul></p><p>Extend delivery mechanisms (can be tested, at least, as “bolt-on” extensions to the bought-in clippings service once it arrives at Powergen). Examples include:<ul><li>Install software at director’s home to retrieve clippings over night and print out personal copy at home in the morning, to allow reading on a journey;<li>Get clippings read out by someone at Powergen and delivered as audio (either by phoning in, or by having directors’ home computers download audio to CD-RW or a portable MP3 player or iPaq) so that the clippings can be listened to safely on a journey.</ul></p>",1, 3,1,2,1,"",""),
new Array(8,"Research/Competitive intelligence database","<p>Source the best competitor intelligence and research and store it in a database with complete version control and a Web publishing system in order to share it effectively.</p><p>This area could also be opened up to other members of the company, such as the “leadership team”, and could be made available (securely) over the Web if appropriate.</p>",3, 3,1,3,3,"Need to make sure the correct permission systems are in place to support this type of venture",""),
new Array(41,"Democratised strategy","<p>A system to ensure, whenever possible, group strategy is defined by a democratic process involving the members of the group.</p><p>When this occurs it helps the group members understand each others’ points of view and gives them a forum to discuss their ideas.</p><p>The hope is that when a strategic decision is made the members will understand the decision and, due to their early involvement, have greater emotional buy-in to that decision.</p>",5, 3,1,1,2,"",""),
new Array(5,"Group area of the intranet","<p>Create a specific part of the intranet dedicated to the Group and its current activities. Objectives include:<ul><li>Deliver basic information about the Group (people, activities, targets);<li>Provide a feedback channel to the group, available to everyone in all the businesses (in fact, cf. “Ask Nick”);<li>Act as a hub that cross-references all of the areas in which the group interacts with the business (for example, by linking into group function-specific intranets).</ul></p><p>The last of these is particularly important, because it provides a platform from which to build entirely new touchpoints between group and businesses that may be cross-function or indepdenent of function.</p>",3, 3,1,3,3,"Need to make sure the correct permission systems are in place to support this type of venture",""),
new Array(3,"Content change alert","<p>Provide a service to allow a user to identify areas of interesting content, such as:<ul><li>Pages of/sections of the Powergen intranet;<li>Pages on the Web;<li>Paper publications.</ul>and be notified when there are updates to these areas.</p><p>This could be implemented with a combination of public Web services, off-the-shelf software for identifying changed content, and people in Powergen carrying out manual checks.</p><p>Such a service provides the user with information about update but, in doing so, collects valuable intelligence about the kinds of things in which users are interested with high precision.</p>",3, 3,2,3,1,"Easy to begin with if controlled by PAs",""),
new Array(15,"Publish group strategy","<p>Make sure that the strategy and objectives of the group and its individual members can be read by others in the group and by the Powergen businesses.</p>",3, 3,1,4,2,"",""),
new Array(9,"Global mobile access to e-mail and documents","<p>Consider mobile communications solutions for iPaqs that address issues of availability and reliability (particularly in the US) and of integration (eg, connections to Notes, to Exchange and to ERP).</p><p>For example, combine the <a href=http://www.a2000d.com/Globe%20Trotter.htm target=_blank>Option Globe Trotter</a> Tri-band GSM/GPRS PC card with a message and document delivery solution delivered through <a href=http://www.aethersystems.com target=_blank>Aether Systems</a>’ mobile platform and worldwide WASP agreements, which also extensively cover the US.</p>",1, 3,2,3,3,"",""),
new Array(31,"Regular directors’ meeting","<p>Create the opportunity for the Group directors to interact regularly. Could either:<ul><li>Have a regular meeting/multi-way video conference to discuss issues; or<li>Have a regular day (once a month?) where directors all agree to spend the day at a particular site, where they (and their PAs) must be provided with proper infrastructure for doing whatever work they wish.</ul></p><p>The latter idea could involve creating a physical shared work environment (or possibly two: one in the US, one in the UK) which would have other uses apart from the regular “directors’ day”.</p>",1, 3,1,1,1,"",""),
new Array(35,"“Fill-in-the-blanks” reporting mechanism","<p>Verbatim from Carol Wood’s remark – a more structured way to handle report entry and workflow around it.</p><p>A neat trick would be to provide a  toolkit to allow those submitting reports to integrate with their own documents.</p><p>So, for example, if I am required to supply cashflow forecast figures, and I normally do that by sending in a spreadsheet to Carol’s team, I may now be asked to enter those figures into a form. In order to help me to do it, I am encouraged to set up a macro in my spreadsheet that copies the relevant content automatically to the structured input mechanism. The toolkit gives me the ability to preview what I've done to make sure it works, and also alerts me if there are any changes to the form that affect its operation.</p><p>By involving those submitting content in this way, some of the work of collating input to reports is distributed down to the businesses.</p>",1, 4,3,3,3,"",""),
new Array(27,"Mobile security","<p>Ensure mobile hardware is properly secure to increase confidence in it. Consider:<ul><li>Encrypted volumes (eg, <A href=http://www.pgp.com target=_blank>PGP</a>);<li>Biometric identification (eg, <a href=http://www.identix.com target=_blank>Identix</a>).</ul></p>",3, 4,1,3,3,"",""),
new Array(23,"“Review before renew” policy","<p>Adopt a policy to ensure that before anything is replaced or renewed a full review of the old system takes place.</p><p>The aim of this policy is to ensure that functionality that is deemed to work gets to stay. This policy will also help to make people realise that they have the power to say what stays and what goes.</p>",4, 4,1,4,2,"",""),
new Array(32,"E-mail etiquette","<p>Provide definition and training for e-mail etiquette. Could do this through:<ul><li>Anecdotal examples;<li>Short, formal training at the desktop;<li>Tools for assessing e-mails for tone and warning of possibly unintentional implications of messages before sending.</ul></p>",1, 4,1,1,1,"",""),
new Array(7,"Association with business initiatives","<p>Provide a service to allow members of the Group to publish areas of interest, and for the businesses to publish summary details of their intiatives, classified by (eg,) subject matter.</p><p>The service would then invite members of the group to take get involved, even if only at the level of basic awareness, in initiatives from the businesses that are relevant to them.</p><p>As well as improving overall awareness, this service provides a medium for direct connection between members of the group and individuals in the businesses.</p>",3, 4,1,2,1,"",""),
new Array(6,"Group “virtual assistants”","<p>Provide a natural language query interface for finding out about the Group and/or individual group functions. The effort required to maintain and evolve the database required to support such a technology may be offset by reduced time dealing with queries; an important benefit, however, is that it provides an excellent mechanism for understanding the kinds of question that the businesses ask.</p><p>A more advanced use of this technology is to provide assistance to individuals in the group who receive questions personally:<ul><li>a virtual assistant could be used to provide automatic responses where clearly possible (for example, in case of a request for a legal form);<li>a virtual assistant could be used to classify incoming messages for easier processing.</ul>This last use has least immediate risk, because the virtual assistant’s output does not appear directly to enquirers.</p><p>An example of this technology is the Lingubot™ from <a href=http://www.kiwilogic.com target=_blank>Kiwilogic</a>.</p>",5, 4,2,3,3,"Need s to be kept up to date and have a mechanism whereby the group can respond to a changing line of questioning",""),
new Array(43,"Job swap/job share","<p>A programme that would enable group members to spend a small amount of their time shadowing or helping out another director with his/her day-to-day work. This could help members better to understand what others in the group do and help them to communicate.</p>",5, 4,1,1,4,"",""),
new Array(16,"Open calendars","<p>Make calendars available to all members of the group. Requires:<ul><li>Everyone to move to an electronic calendar <font face=symbol>&#222;</font> training for this, including the addressing of the deficiencies of the electronic calendar with respect to a paper-based system;<li>Everyone to agree to do this.</ul></p>",1, 4,1,4,1,"In order for this to be a success the PAs and the Directors themselves must ensure the shared electronic diaries are always kept up to date",""),
new Array(4,"Peer assist programme","<p>Use a tool, developed originally at BP, that is used to teach teamwork and the larger view. Instead of bringing in an expert to solve a team’s problem, peers operate in a shared learning environment. In this environment, workers are strongly encouraged to move beyond a focus on their particular personal or departmental concerns and to treat all teammates as collaborators in a common cause.</p><p><i>“We reward people for how well they work with others. One of the criteria for moving up to more senior levels in the organization is how well you deliver on that particular metric.”<br>&#151; Atul Arya, Group Planning Manager, BP</i></p>",4, 4,3,4,4,"Needs cultural re-enforcement",""),
new Array(22,"Profiles","<p>Provide a directory service containing profiles of people that begin by showing photos, contact details, and responsibilities but can be extended to include:<ul><li>expertise;<li>interests;<li>business network involvement;<li>objectives;<li>details supplied by an expertise profile building Q&A system like <a href=http://www.orbitalsw.com target=_blank>Orbital</a>.</ul></p><p>This sophisticated profile then lends itself to other functionality like powering recommendation engines,“people like me” functions and expertise searching.</p>",5, 4,4,5,4,"",""),
new Array(12,"Business networks","<p>Provide a service to identify groups of like-minded individuals to promote collaboration and sharing of knowledge and expertise.</p><p>The matching of interests depends on capturing them in the first place; this can be achieved by some combination of:<ul><li>Explicit declaration &#151; individuals enter their interests and keep them up-to-date;<li>Explicit rating &#151; individuals explicitly rate interest levels in information they read;<li>Inference from read/produced content &#151; the service guesses interest areas by looking at the documents each individual reads and produces;<li>Inference from communications and other behaviour &#151; the service guesses (relative) affiliations by looking at communication and other behavioural patterns within the community of its users.</ul></p>It is important to combine the inferred methods with appropriate feedback to users, so that they can contribute to the accuracy of the process by rating/modifying the inferences that have been made visible.</p><p>An end goal of such a service is to create <i>communities</i> which are “super experts” in their fields, and which can act in this way.<p>",5, 4,4,4,2,"There are large cultural implications in ensuring this type of initiative works",""),
new Array(36,"Engineering intranet redesign","<p>Address the issues raised by the engineering function, which include:<ul><li>Lack of a content-management system;<li>Non-intuitive interface;<li>Needs improved ability to alert users of changes to content relevant to them.</ul></p>",5, 5,3,3,3,"",""),
new Array(37,"Electronic document retrieval","<p>Explore ways of dealing more efficiently with the large volume of paper documents handled by the legal team. Key issues include:<ul><li>Access to archived documents is frequent;<li>Accuracy of indexing is probably a limiting factor with current technology and procedures (cf. Oracle’s legal department).</ul></p>",1, 5,3,3,3,"",""),
new Array(38,"Automatic messaging to press","<p>Provide a service that can send a release to all key press contacts, selected by relevance and urgency, through appropriate routes (e-mail, fax, SMS alert).</p><p>Helps to build direct relationships with press. Should also save money compared to currently outsourced service.</p>",5, 5,3,3,3,"",""),
new Array(39,"Modular media training","<p>Provide “refresher” media training at the desktop.</p><p>Could use “interactive video interviews”, in which Oyster has done pioneering work.</p>",5, 5,3,6,2,"",""),
new Array(40,"Internet intelligence","<p>Investigate the use of an Internet intelligence company to provide extra warning of impending issues.</p><p>Services from companies such as <a href=http://www.infonic.com target=_blank>Infonic</a> monitor news groups, chat rooms etc. and can provide significantly earlier warning than reactive services that announce breaking stories.</p><p>Read an example piece <a href=download/infonic_sample.pdf target=_blank>[PDF]</a> <a href=download/infonic_sample.doc target=_blank>[Microsoft Word]</a>.</p>",5, 5,3,3,3,"","")

);

function getIdeaIndexFromID(ideaID)
{
	var i;

	for (i=0; i < ideas.length; i++)
		if (ideas[i][0] == ideaID)
			return i;

	return -1;
}