// each idea contains an issue ID, a person ID, a commentary and a highlight string
var issueNoteLinks = new Array(
new Array(1,2,"Security is not an issue for David. It is David&#146;s use of a number of different e-mail accounts that is the real issue.","5,6"),
new Array(4,1,"Directors are too independent and don&#145;t make the best use of each others skills.","14"),
new Array(5,1,"","15"),
new Array(6,1,"Nick wants to clarify the role and objectives of the group.","11,13,14,17,18,19"),
new Array(37,1,"Uses personal mail from home because has not yet got the corporate mail to work.","5"),
new Array(1,1,"Uses personal mail from home because has not yet got the corporate mail to work.","5"),
new Array(39,1,"","7"),
new Array(40,1,"","3,4,6,16"),
new Array(41,1,"Nick seems exasperated by the usefulness of the intranet.","3,4"),
new Array(42,1,"Nick is aware of several areas of the group image that he feels need to change.","12,17,19"),
new Array(44,1,"","15"),
new Array(45,1,"Nick is encouraging other directors to open their calendars by making his own available.","13"),
new Array(3,2,"David feels searching the intranet and downloading documents are both a waste of time.","7,17"),
new Array(4,2,"Having more than one office leads to lack of interaction and a failure to use the knowledge of others to answers questions.","19"),
new Array(6,2,"David feels the culture of the group needs to change to one where communication is key.","29"),
new Array(37,2,"It seems like some of David&#146;s problems could be solved with basic training.","5,6,10,13,23"),
new Array(40,2,"","7,11"),
new Array(41,2,"David does not have confidence in the intranet.","12,17"),
new Array(42,2,"David feels the group is young and still needs to develop its culture and levels of communication.","25,30"),
new Array(43,2,"A sending culture can lead to superfluous information being sent just in case.","29"),
new Array(44,2,"New ways to conduct meetings could be useful.","21"),
new Array(45,2,"Working on multiple sites seriously reduces access to other directors.","3,18,19,27"),
new Array(45,3,"","25"),
new Array(37,3,"It seems like some of David&#146;s problems could be solved with basic training.","26,29"),
new Array(41,3,"David is more likely to search for information and keep his schedule up to date if it is easier for him to do so.","27,30"),
new Array(4,6,"Jonathan feel the group has a responsibility to transfer expertise.","11,16"),
new Array(6,6,"","19"),
new Array(42,6,"Most of Jonathans issues are concerned with the how the group can demonstrate added value to the businesses.","6,10,12,14,15,16,17,18"),
new Array(45,6,"Effective communication and casual interaction are both issues for Jonathan.","4,5,6"),
new Array(4,7,"Understanding what everybody does and how they can best be utilized is key for John.","3,17,19"),
new Array(37,7,"John identifies a training/coaching need that has not yet been addressed.","20,26"),
new Array(39,7,"Before moving forward, John feels, the group needs to look more closely at what has been done with technology so far.","7"),
new Array(40,7,"","4"),
new Array(42,7,"John feels the group image should be built around relationships.","5"),
new Array(1,8,"","28"),
new Array(3,8,"Publishing research documents and downloading files are both a waste of time.","30,32"),
new Array(40,8,"Transatlantic travel makes connectivity a big issue for Chris.","3,8,11,12"),
new Array(41,8,"Chris would benefit from information being brought to him rather than having to search for it.","10"),
new Array(43,8,"Chris would benefit from information being brought to him rather than having to search for it.","10"),
new Array(45,8,"Chris like the idea of open calendars and is leading by example.","6"),
new Array(4,8,"Knowing what people do would help Chris organize collaborative projects.","25,36"),
new Array(5,9,"The lack of consolidated communication suggests a lack of information continuity through the group.","17"),
new Array(37,9,"","9,16"),
new Array(40,9,"","3"),
new Array(41,9,"This statement suggest that more could be done to bring press related information to the directors.","16"),
new Array(42,9,"Big picture understanding and image is a big issue for Gareth.","22"),
new Array(3,10,"Downloading documentation remotely and &#147;the rest of the crap&#148; seem like the main waste of time for Carol.","4,6,10"),
new Array(4,10,"This comment suggest Carol doesn&#146;t feel she is getting the best out of the other directors.","3"),
new Array(6,10,"Carol feel the directors and business objectives need to be made clearer.","17"),
new Array(40,10,"Carol has issues with connectivity. These could become more pronounced if, as Carol suggests, directors should spend half their time in the US.","5,6,7"),
new Array(41,10,"The performance report is not as widely available as Carol feels it should be.","16"),
new Array(42,10,"Carol wants to justify the group using performance metrics.","13"),
new Array(45,10,"This comment suggests Carol does not feel the access to other directors is not high enough.","3"),
new Array(3,12,"","7"),
new Array(4,12,"Getting the right people in place to undertake the different stages of the deal is a key issue for Caroline.","10,14,16,22"),
new Array(41,12,"This comment suggests the data needed is sometimes not available when it is needed.","17"),
new Array(40,12,"Caroline and her team need 24 hour a day &#147;fully mobile&#148; connectivity.","4,17"),
new Array(6,12,"These strategic objectives need to be made clear to all the other directors and the rest of the company.","9"),
new Array(37,13,"It seems that Caroline may benefit if Audrey went on more technical training.","18,22"),
new Array(45,13,"Audrey feels like she would benefit from sitting together with other group directors as well as Caroline.","20"),
new Array(3,14,"Karen feels that updating the archive filing system manually is a waste of time.","22,23,24"),
new Array(40,14,"","27"),
new Array(4,14,"Karen feels she could offer a better service if she was involved earlier on in projects.","26"),
new Array(3,15,"","11"),
new Array(40,15,"Kim feels improvements of connectivity that enable Nick to access documentation on the move would be helpful.","6"),
new Array(44,15,"This comment suggests comprehensive meeting preparation does not take place on some occasions.","7"),
new Array(45,16,"Mary&#146;s lack of interaction with the rest of the group could prove a problem in the future.","3"),
new Array(47,1,"","14"),
new Array(5,2,"","29,30"),
new Array(5,6,"","9"),
new Array(5,10,"","16"),
new Array(5,15,"This initiative indicates there is not a significant level of sharing between PA&#146;s.","8")

);
